config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  resources :tasks do
    resources :comments, only: [ :create, :destroy ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
  validates :text, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :show, :edit, :update, :destroy ]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end
  
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    if @task.save!
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @task.update(task_params)
      redirect_to dashboard_path
    else
      render :new
    end
  end
  
  def destroy
    @task.destroy
    redirect_to dashboard_path
  end

  private

  def task_params
    params.require(:task).permit(:title)
  end

  def set_task
    @task = Task.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifeAdminRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">

  <div class="left-container">
    <h2>Dashboard</h2>

    <div class="tasks">
      <% current_user.tasks.each do |task| %>
        <p>
          <%# <%= link_to task.done ? "✔" : "❌", task_path(task), method: :task_done? %>
          
          <%= task.title %>
          <%= link_to '☠', task_path(task), class: "btn del",
                method: :delete,
                data: { confirm: "Are you sure?" } %>
        </p>
      <% end %>
    </div>

    <%= link_to "New Task", new_task_path, class: "btn btn-primary" %>
  </div>

</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/jessica-pring", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "New Task", new_task_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto" style="width: 400px;">
      <h2 style="text-align: center;">Edit Task</h2>
      <%= simple_form_for @task do |f| %>
        <%= f.input :title %>
        <%= f.submit "Update Task", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<h2>Tasks Index</h2>

<ol>
  <% @tasks.each do |task| %>
    <li><%= task.title %> - <%= link_to 'Delete', task_path(task), class: "btn btn-outline-danger",
            method: :delete,
            data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ol>

<%= link_to "New Task", new_task_path, class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto" style="width: 400px;">
      <h2 style="text-align: center;">New Task</h2>
      <%= simple_form_for @task do |f| %>
        <%= f.input :title %>
        <%= f.submit "Create Task", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>